# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PasswordStorage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'RxSwift', '4.0'
   pod 'RxCocoa', '4.0'
   pod 'IQKeyboardManagerSwift', '5.0.0'
   pod 'KeychainSwift', '10.0'
   pod 'DZNEmptyDataSet', '1.7.3'
   pod 'Kingfisher', '4.6'

  target 'PasswordStorageTests' do
    inherit! :search_paths
    
  end

  target 'PasswordStorageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
